import type {
  GetMessagesArgs,
  Resource,
  Store,
  Thread,
} from '@chituma/core/store'
import type { ChitumaMessage, MessageRole } from '@chituma/core'

/**
 * Minimal query interface shared by `pg.Pool`, `pg.Client` and `PGlite`.
 * Anything exposing `query(text, params)` returning `{ rows }` works, which
 * keeps the store decoupled from a live Postgres for tests.
 */
export type SqlExecutor = {
  query(text: string, params?: unknown[]): Promise<{ rows: any[] }>
}

export type PgStoreOptions =
  | { connectionString: string; client?: never }
  | { client: SqlExecutor; connectionString?: never }

const THREADS = 'chituma_threads'
const MESSAGES = 'chituma_messages'
const RESOURCES = 'chituma_resources'
const SNAPSHOTS = 'chituma_snapshots'

/** Serialize a JSON value for a jsonb column, mapping `undefined` to NULL. */
function toJson(value: unknown): string | null {
  return value === undefined || value === null ? null : JSON.stringify(value)
}

/**
 * Read a jsonb column. Both `pg` and `PGlite` already parse jsonb into JS
 * values, so we only map NULL → undefined and pass the parsed value through.
 */
function parseJson<T>(value: unknown): T | undefined {
  return value === null || value === undefined ? undefined : (value as T)
}

/** Coerce a timestamptz column (Date or ISO string) into a `Date`. */
function reviveDate(value: unknown): Date {
  return value instanceof Date ? value : new Date(value as string)
}

/**
 * PostgreSQL-backed {@link Store}. Pass `connectionString` to lazily create a
 * `pg.Pool`, or `client` to reuse an existing executor (e.g. `PGlite`).
 */
export class PgStore implements Store {
  private executor?: SqlExecutor
  private executorPromise?: Promise<SqlExecutor>
  private readonly connectionString?: string
  private initPromise?: Promise<void>

  constructor(opts: PgStoreOptions) {
    if (opts.client) {
      this.executor = opts.client
    } else {
      this.connectionString = opts.connectionString
    }
  }

  private async getExecutor(): Promise<SqlExecutor> {
    if (this.executor) return this.executor
    if (!this.executorPromise) {
      const connectionString = this.connectionString
      this.executorPromise = import('pg').then(({ default: pg }) => {
        this.executor = new pg.Pool({ connectionString })
        return this.executor
      })
    }
    return this.executorPromise
  }

  private async query(text: string, params?: unknown[]): Promise<any[]> {
    const db = await this.getExecutor()
    const { rows } = await db.query(text, params)
    return rows
  }

  /** Lazily create tables on first use. Safe to call repeatedly. */
  async init(): Promise<void> {
    if (!this.initPromise) this.initPromise = this.runInit()
    return this.initPromise
  }

  private async runInit(): Promise<void> {
    const db = await this.getExecutor()
    await db.query(`
      CREATE TABLE IF NOT EXISTS ${THREADS} (
        id text PRIMARY KEY,
        resource_id text NOT NULL,
        title text,
        metadata jsonb,
        created_at timestamptz NOT NULL,
        updated_at timestamptz NOT NULL
      );
    `)
    await db.query(
      `CREATE INDEX IF NOT EXISTS ${THREADS}_resource_id_idx ON ${THREADS} (resource_id);`,
    )
    await db.query(`
      CREATE TABLE IF NOT EXISTS ${MESSAGES} (
        id text PRIMARY KEY,
        thread_id text NOT NULL,
        resource_id text,
        role text NOT NULL,
        content jsonb NOT NULL,
        created_at timestamptz NOT NULL,
        ordinal bigint GENERATED BY DEFAULT AS IDENTITY
      );
    `)
    await db.query(
      `CREATE INDEX IF NOT EXISTS ${MESSAGES}_thread_id_idx ON ${MESSAGES} (thread_id, created_at, ordinal);`,
    )
    await db.query(`
      CREATE TABLE IF NOT EXISTS ${RESOURCES} (
        id text PRIMARY KEY,
        working_memory text,
        metadata jsonb
      );
    `)
    await db.query(`
      CREATE TABLE IF NOT EXISTS ${SNAPSHOTS} (
        key text PRIMARY KEY,
        value jsonb NOT NULL,
        updated_at timestamptz NOT NULL
      );
    `)
  }

  // ── threads ──────────────────────────────────────────────────────────────

  async saveThread(thread: Thread): Promise<Thread> {
    await this.init()
    await this.query(
      `INSERT INTO ${THREADS} (id, resource_id, title, metadata, created_at, updated_at)
       VALUES ($1, $2, $3, $4, $5, $6)
       ON CONFLICT (id) DO UPDATE SET
         resource_id = EXCLUDED.resource_id,
         title = EXCLUDED.title,
         metadata = EXCLUDED.metadata,
         created_at = EXCLUDED.created_at,
         updated_at = EXCLUDED.updated_at`,
      [
        thread.id,
        thread.resourceId,
        thread.title ?? null,
        toJson(thread.metadata),
        thread.createdAt.toISOString(),
        thread.updatedAt.toISOString(),
      ],
    )
    return thread
  }

  async getThread(id: string): Promise<Thread | null> {
    await this.init()
    const rows = await this.query(`SELECT * FROM ${THREADS} WHERE id = $1`, [id])
    const row = rows[0]
    return row ? this.rowToThread(row) : null
  }

  async getThreadsByResourceId(resourceId: string): Promise<Thread[]> {
    await this.init()
    const rows = await this.query(
      `SELECT * FROM ${THREADS} WHERE resource_id = $1 ORDER BY created_at ASC`,
      [resourceId],
    )
    return rows.map((r) => this.rowToThread(r))
  }

  async deleteThread(id: string): Promise<void> {
    await this.init()
    await this.query(`DELETE FROM ${MESSAGES} WHERE thread_id = $1`, [id])
    await this.query(`DELETE FROM ${THREADS} WHERE id = $1`, [id])
  }

  private rowToThread(row: any): Thread {
    return {
      id: row.id,
      resourceId: row.resource_id,
      title: row.title ?? undefined,
      metadata: parseJson<Record<string, unknown>>(row.metadata),
      createdAt: reviveDate(row.created_at),
      updatedAt: reviveDate(row.updated_at),
    }
  }

  // ── messages ─────────────────────────────────────────────────────────────

  async saveMessages(messages: ChitumaMessage[]): Promise<ChitumaMessage[]> {
    await this.init()
    if (messages.length === 0) return messages

    const cols = 6
    const values: unknown[] = []
    const placeholders = messages
      .filter((m) => m.threadId)
      .map((m, i) => {
        const base = i * cols
        values.push(
          m.id,
          m.threadId,
          m.resourceId ?? null,
          m.role,
          toJson(m.content),
          m.createdAt.toISOString(),
        )
        return `($${base + 1}, $${base + 2}, $${base + 3}, $${base + 4}, $${base + 5}, $${base + 6})`
      })

    if (placeholders.length === 0) return messages

    await this.query(
      `INSERT INTO ${MESSAGES} (id, thread_id, resource_id, role, content, created_at)
       VALUES ${placeholders.join(', ')}
       ON CONFLICT (id) DO UPDATE SET
         thread_id = EXCLUDED.thread_id,
         resource_id = EXCLUDED.resource_id,
         role = EXCLUDED.role,
         content = EXCLUDED.content,
         created_at = EXCLUDED.created_at`,
      values,
    )
    return messages
  }

  async getMessages({ threadId, last }: GetMessagesArgs): Promise<ChitumaMessage[]> {
    await this.init()
    let rows: any[]
    if (typeof last === 'number') {
      rows = await this.query(
        `SELECT * FROM (
           SELECT * FROM ${MESSAGES}
           WHERE thread_id = $1
           ORDER BY created_at DESC, ordinal DESC
           LIMIT $2
         ) sub
         ORDER BY created_at ASC, ordinal ASC`,
        [threadId, last],
      )
    } else {
      rows = await this.query(
        `SELECT * FROM ${MESSAGES}
         WHERE thread_id = $1
         ORDER BY created_at ASC, ordinal ASC`,
        [threadId],
      )
    }
    return rows.map((r) => this.rowToMessage(r))
  }

  private rowToMessage(row: any): ChitumaMessage {
    return {
      id: row.id,
      role: row.role as MessageRole,
      content: parseJson<ChitumaMessage['content']>(row.content) as ChitumaMessage['content'],
      createdAt: reviveDate(row.created_at),
      threadId: row.thread_id ?? undefined,
      resourceId: row.resource_id ?? undefined,
    }
  }

  // ── resources ────────────────────────────────────────────────────────────

  async getResource(id: string): Promise<Resource | null> {
    await this.init()
    const rows = await this.query(`SELECT * FROM ${RESOURCES} WHERE id = $1`, [id])
    const row = rows[0]
    if (!row) return null
    return {
      id: row.id,
      workingMemory: row.working_memory ?? undefined,
      metadata: parseJson<Record<string, unknown>>(row.metadata),
    }
  }

  async saveResource(resource: Resource): Promise<Resource> {
    await this.init()
    await this.query(
      `INSERT INTO ${RESOURCES} (id, working_memory, metadata)
       VALUES ($1, $2, $3)
       ON CONFLICT (id) DO UPDATE SET
         working_memory = EXCLUDED.working_memory,
         metadata = EXCLUDED.metadata`,
      [resource.id, resource.workingMemory ?? null, toJson(resource.metadata)],
    )
    return resource
  }

  // ── snapshots (generic kv) ───────────────────────────────────────────────

  async persistSnapshot(key: string, value: unknown): Promise<void> {
    await this.init()
    await this.query(
      `INSERT INTO ${SNAPSHOTS} (key, value, updated_at)
       VALUES ($1, $2, $3)
       ON CONFLICT (key) DO UPDATE SET
         value = EXCLUDED.value,
         updated_at = EXCLUDED.updated_at`,
      [key, toJson(value), new Date().toISOString()],
    )
  }

  async loadSnapshot<T = unknown>(key: string): Promise<T | null> {
    await this.init()
    const rows = await this.query(`SELECT value FROM ${SNAPSHOTS} WHERE key = $1`, [key])
    const row = rows[0]
    if (!row) return null
    return (parseJson<T>(row.value) ?? null) as T | null
  }
}
